[2020-06-28 07:34:14,534] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-28T02:02:58.754609+00:00 [queued]>
[2020-06-28 07:34:14,542] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-28T02:02:58.754609+00:00 [queued]>
[2020-06-28 07:34:14,542] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 07:34:14,542] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-28 07:34:14,542] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 07:34:14,550] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): get_covid_data_task> on 2020-06-28T02:02:58.754609+00:00
[2020-06-28 07:34:14,552] {standard_task_runner.py:53} INFO - Started process 17029 to run task
[2020-06-28 07:34:14,591] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-28T02:02:58.754609+00:00 [running]> localhost.localdomain
[2020-06-28 07:34:14,769] {logging_mixin.py:112} INFO - API Data is valid
[2020-06-28 07:34:20,100] {logging_mixin.py:112} INFO - Covid Statewise Data CSV is uploaded to HDFS
[2020-06-28 07:34:20,101] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-28 07:34:20,105] {taskinstance.py:1052} INFO - Marking task as SUCCESS.dag_id=covid_data_dag, task_id=get_covid_data_task, execution_date=20200628T020258, start_date=20200628T020414, end_date=20200628T020420
[2020-06-28 07:34:24,531] {logging_mixin.py:112} INFO - [2020-06-28 07:34:24,530] {local_task_job.py:103} INFO - Task exited with return code 0
