[2020-06-23 15:20:47,368] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-23T09:48:57.115772+00:00 [queued]>
[2020-06-23 15:20:47,375] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-23T09:48:57.115772+00:00 [queued]>
[2020-06-23 15:20:47,375] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-23 15:20:47,375] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-23 15:20:47,375] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-23 15:20:47,382] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): get_covid_data_task> on 2020-06-23T09:48:57.115772+00:00
[2020-06-23 15:20:47,384] {standard_task_runner.py:53} INFO - Started process 41899 to run task
[2020-06-23 15:20:47,422] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-23T09:48:57.115772+00:00 [running]> localhost.localdomain
[2020-06-23 15:20:47,801] {logging_mixin.py:112} INFO - API Data is valid
[2020-06-23 15:20:47,806] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-23 15:20:47,809] {taskinstance.py:1052} INFO - Marking task as SUCCESS.dag_id=covid_data_dag, task_id=get_covid_data_task, execution_date=20200623T094857, start_date=20200623T095047, end_date=20200623T095047
[2020-06-23 15:20:57,371] {logging_mixin.py:112} INFO - [2020-06-23 15:20:57,370] {local_task_job.py:103} INFO - Task exited with return code 0
