[2020-06-22 15:04:56,768] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-22T09:33:23.039282+00:00 [queued]>
[2020-06-22 15:04:56,776] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-22T09:33:23.039282+00:00 [queued]>
[2020-06-22 15:04:56,776] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-22 15:04:56,776] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-22 15:04:56,776] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-22 15:04:56,783] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): get_covid_data_task> on 2020-06-22T09:33:23.039282+00:00
[2020-06-22 15:04:56,785] {standard_task_runner.py:53} INFO - Started process 16865 to run task
[2020-06-22 15:04:56,824] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_data_dag.get_covid_data_task 2020-06-22T09:33:23.039282+00:00 [running]> localhost.localdomain
[2020-06-22 15:04:56,937] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-22 15:04:56,946] {taskinstance.py:1052} INFO - Marking task as SUCCESS.dag_id=covid_data_dag, task_id=get_covid_data_task, execution_date=20200622T093323, start_date=20200622T093456, end_date=20200622T093456
[2020-06-22 15:05:06,769] {logging_mixin.py:112} INFO - [2020-06-22 15:05:06,768] {local_task_job.py:103} INFO - Task exited with return code 0
